
const f=()=>{

    try{
        let a = 0;
        // console.log(program)
        console.log("program run sucess full")
        return 
    }
    catch(err){
        console.log("This is an error")
        console.log(p)
    }
    finally{
        console.log("I am a good boy")
        //close the file
        //Exit the loop
        //write to the log file
    }
}
f()